export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

export const GET_VERIFIED_USERS_REQUEST = "GET_VERIFIED_USERS_REQUEST";
export const GET_VERIFIED_USERS_SUCCESS = "GET_VERIFIED_USERS_SUCCESS";
export const GET_VERIFIED_USERS_FAILURE = "GET_VERIFIED_USERS_FAILURE";

export const GET_NON_VERIFIED_USERS_REQUEST = "GET_NON_VERIFIED_USERS_REQUEST";
export const GET_NON_VERIFIED_USERS_SUCCESS = "GET_NON_VERIFIED_USERS_SUCCESS";
export const GET_NON_VERIFIED_USERS_FAILURE = "GET_NON_VERIFIED_USERS_FAILURE";
